import path from "node:path";
import { existsSync, readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { createPropsRigTargetCatalog, importGltfAnimations } from "..";
import {
  bundleAnimationEntryToClipIr,
  clipIrToBundleAnimationEntry,
} from "../../utils/animationClipCompiler";
import type { AnimationClipIR } from "../../types/animationClipIr";
import { modelGeometryDerivedInputPaths } from "./makeGlb";
import { readGlbJson } from "./readGlbJson";

const ASSET_DIR = path.resolve(__dirname, "../../../public/assets");
const assetPath = (name: string) => path.join(ASSET_DIR, name);

function readArrayBuffer(name: string): ArrayBuffer {
  const buffer = readFileSync(assetPath(name));
  return buffer.buffer.slice(
    buffer.byteOffset,
    buffer.byteOffset + buffer.byteLength,
  ) as ArrayBuffer;
}

function importClip(file: string): AnimationClipIR {
  const json = readGlbJson(assetPath(file));
  const catalog = createPropsRigTargetCatalog(
    modelGeometryDerivedInputPaths(json),
  );
  const { clips } = importGltfAnimations({
    glb: readArrayBuffer(file),
    catalog,
  });
  return clips[0]!;
}

/** Comparable shape: ids are regenerated by design, values are not. */
function fingerprint(clip: AnimationClipIR) {
  return {
    duration: clip.duration,
    tracks: [...clip.tracks]
      .sort((left, right) => left.channel.localeCompare(right.channel))
      .map((track) => ({
        channel: track.channel,
        variableId: track.variableId,
        interpolation: track.interpolation,
        keyframes: track.keyframes.map((keyframe) => ({
          time: keyframe.time,
          value: keyframe.value,
          interpolation: keyframe.interpolation ?? null,
          inTangent: keyframe.inTangent ?? null,
          outTangent: keyframe.outTangent ?? null,
        })),
      })),
  };
}

const FILES = [
  "Quori_Latest_Blender_Export.glb",
  "Hugo_Latest_Blender_Export.glb",
  "Toasty_Latest_Blender_Export.glb",
] as const;

const available = FILES.every((file) => existsSync(assetPath(file)));

/**
 * Round-trips an imported clip through the Vizij bundle — the authoritative
 * storage form, and the path an exported GLB actually carries animation in.
 *
 * Note this does NOT cover baking to native glTF animation channels: that
 * requires graph sampling and is not implemented yet
 * (see plans/GLB_ANIMATION_ROUNDTRIP_PLAN_2026-09-02.md phase 3).
 */
describe.runIf(available)("import -> bundle -> import round trip", () => {
  it.each(FILES)("%s survives a bundle round trip unchanged", (file) => {
    const imported = importClip(file);
    const entry = clipIrToBundleAnimationEntry(imported);
    const restored = bundleAnimationEntryToClipIr(entry);

    expect(restored).not.toBeNull();
    expect(fingerprint(restored!)).toEqual(fingerprint(imported));
  });

  it.each(FILES)("%s is idempotent over a second round trip", (file) => {
    const first = bundleAnimationEntryToClipIr(
      clipIrToBundleAnimationEntry(importClip(file)),
    )!;
    const second = bundleAnimationEntryToClipIr(
      clipIrToBundleAnimationEntry(first),
    )!;
    // A second pass must not drift: no accumulating quantization, no channel
    // renaming, no keyframe loss.
    expect(fingerprint(second)).toEqual(fingerprint(first));
  });

  it("preserves the exact keyframe values of Toasty's blink", () => {
    const imported = importClip("Toasty_Latest_Blender_Export.glb");
    const restored = bundleAnimationEntryToClipIr(
      clipIrToBundleAnimationEntry(imported),
    )!;
    const channel = "propsrig/l_tlid/lid_updn/value";
    const before = imported.tracks.find((t) => t.channel === channel)!;
    const after = restored.tracks.find((t) => t.channel === channel)!;

    expect(after.keyframes.map((k) => k.value)).toEqual(
      before.keyframes.map((k) => k.value),
    );
    expect(after.keyframes.map((k) => k.time)).toEqual(
      before.keyframes.map((k) => k.time),
    );
    // The blink really is 1 -> 0 -> 1, not a flat zero.
    expect(Math.min(...after.keyframes.map((k) => k.value))).toBeCloseTo(0, 6);
    expect(Math.max(...after.keyframes.map((k) => k.value))).toBeCloseTo(1, 6);
  });

  it("preserves rotation tracks through the bundle", () => {
    const imported = importClip("Quori_Latest_Blender_Export.glb");
    const restored = bundleAnimationEntryToClipIr(
      clipIrToBundleAnimationEntry(imported),
    )!;
    const rotationChannels = restored.tracks
      .filter((track) => track.channel.includes("/rotation/"))
      .map((track) => track.channel)
      .sort();
    expect(rotationChannels).toEqual([
      "propsrig/ltlid/rotation/x",
      "propsrig/ltlid/rotation/y",
      "propsrig/ltlid/rotation/z",
      "propsrig/rtlid/rotation/x",
      "propsrig/rtlid/rotation/y",
      "propsrig/rtlid/rotation/z",
    ]);
    // Still continuous after the round trip — no 2π reintroduced.
    for (const track of restored.tracks.filter((t) =>
      t.channel.includes("/rotation/"),
    )) {
      for (let i = 1; i < track.keyframes.length; i += 1) {
        expect(
          Math.abs(track.keyframes[i]!.value - track.keyframes[i - 1]!.value),
        ).toBeLessThan(Math.PI);
      }
    }
  });

  it("excludes detached tracks from the bundle but keeps the rest", () => {
    const imported = importClip("Toasty_Latest_Blender_Export.glb");
    const withDetached: AnimationClipIR = {
      ...imported,
      tracks: imported.tracks.map((track, index) =>
        index === 0 ? { ...track, detached: true } : track,
      ),
    };
    const entry = clipIrToBundleAnimationEntry(withDetached);
    expect(entry.clip.tracks).toHaveLength(imported.tracks.length - 1);
    expect(
      entry.clip.tracks.some(
        (track) => track.channel === imported.tracks[0]!.channel,
      ),
    ).toBe(false);
  });

  it("carries cubic tangents through the bundle", () => {
    // The corpus is entirely LINEAR, so this uses a synthetic cubic clip to
    // prove the bundle does not silently drop tangents.
    const clip: AnimationClipIR = {
      schemaVersion: 1,
      id: "cubic",
      name: "cubic",
      duration: 2,
      tracks: [
        {
          id: "t0",
          variableId: "propsrig_lid_translation_x",
          channel: "propsrig/lid/translation/x",
          interpolation: "cubic",
          keyframes: [
            { id: "k0", time: 0, value: 0, inTangent: 1, outTangent: 2 },
            { id: "k1", time: 2, value: 1, inTangent: 3, outTangent: 4 },
          ],
        },
      ],
    };
    const restored = bundleAnimationEntryToClipIr(
      clipIrToBundleAnimationEntry(clip),
    )!;
    const track = restored.tracks[0]!;
    expect(track.interpolation).toBe("cubic");
    expect(track.keyframes.map((k) => [k.inTangent, k.outTangent])).toEqual([
      [1, 2],
      [3, 4],
    ]);
  });
});
