name: ci
on:
  push:
  pull_request:

concurrency:
  group: web-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.2
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build:packages
      - run: pnpm run format:check
      - run: pnpm run lint:all
      - run: pnpm run typecheck:all
      - run: pnpm run test:all
      - run: pnpm run build
